### ISSUE TITLE
Hello sir

### ISSUE THREAD

**Issue by dr1408** [SpacingBat3/android_kernel_samsung-m127f_a13#1]
Is there is anyone for A137F

**Comment by SpacingBat3** [comment]
Nope. I only maintain and build kernels for my personal use, this means only M127F and no other phone – and I'll drop the support once I'll move to another phone or Samsung will drop security updates, I guess I might experiment with backporting the newer/upstream kernels to this phone, but right now I'm not sure if that'll be effortless, Samsung modifies a bunch of files and with the way they release their kernels, I'm a bit lost which changes they just backport to their kernel and which are their own. I've also never worked around the kernel sources too much, although I have some knowledge about C and its syntax.
And this project is made to be a bit opinionated, I guess there are some people who might find other kernel builds a bit more beneficial for them.
